### ISSUE TITLE
Won't accept Python version

### ISSUE THREAD

**Issue by leopheard** [jessedp/pihole5-list-tool#24]
## Environment
Describe the system on which this issue occurred:
**pihole5-list-tool** _(ex: 0.4.2, `pip3 show pihole5-list-tool`)_ **:**
**OS** _(ex: Ubuntu 20.20, `lsb_release -a`)_ **:** Rasbpian 9.11
**Python** _(ex: 3.8.2, `python --version`)_ **:** 3.8.0
**Using Docker?** No
.....**version** _(ex: 19.03.10, `docker -v`)_ **:**

Hi all,

So running Python -V gives "Python 3.8.0" but running _sudo pip3 install pihole5-list-tool --upgrade_ produces "this tool requires 3.6 or greater, you are running 3.5.3". What am I doing wrong? I've just upgraded, followed the guide here: https://installvirtual.com/how-to-install-python-3-8-on-raspberry-pi-raspbian/ rebooted and it's still not showing the correct version?

**Comment by jessedp** [comment]
Step 6 is the "problem" and fix. When you did that it only changed it for the current user, not the root user, which is used when running sudo. You can verify that further by running `sudo python -V`.

At least 2 options:
- Do # 6 again like this:
`echo "alias python=/usr/local/bin/python3.8" >> /root/.bashrc`

- Make the new python the system default following something like [this](https://linuxconfig.org/change-default-python-version-on-raspbian-gnu-linux) . Since they are both Python 3, that _should_ be safe.
